export const GET_BOOKINGS_START = 'GET_BOOKINGS_START',
                GET_BOOKINGS_SUCCESS = 'GET_BOOKINGS_SUCCESS',
                GET_BOOKINGS_FAILURE = 'GET_BOOKINGS_FAILURE';

export const CONFIRM_BOOKINGS_START = 'CONFIRM_BOOKINGS_START',
                CONFIRM_BOOKINGS_SUCCESS = 'CONFIRM_BOOKINGS_SUCCESS',
                CONFIRM_BOOKINGS_FAILURE = 'CONFIRM_BOOKINGS_FAILURE';

export const CREATE_BOOKING_START = 'CREATE_BOOKING_START',
                CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS',
                CREATE_BOOKING_FAILURE = 'CREATE_BOOKING_FAILURE';

export const DECLINE_BOOKING_START = 'DECLINE_BOOKING_START',
                DECLINE_BOOKING_SUCCESS = 'DECLINE_BOOKING_SUCCESS',
                DECLINE_BOOKING_FAILURE = 'DECLINE_BOOKING_FAILURE';

export const GET_ALL_BOOKINGS_FOR_USER_START = 'GET_ALL_BOOKINGS_FOR_USER_START',
                GET_ALL_BOOKINGS_FOR_USER_SUCCESS = 'GET_ALL_BOOKINGS_FOR_USER_SUCCESS',
                GET_ALL_BOOKINGS_FOR_USER_FAILURE = 'GET_ALL_BOOKINGS_FOR_USER_FAILURE';