export const    GET_BOOKINGS_START = 'GET_BOOKINGS_START',
                GET_BOOKINGS_SUCCESS = 'GET_BOOKINGS_SUCCESS',
                GET_BOOKINGS_FAILURE = 'GET_BOOKINGS_FAILURE';

export const    CONFIRM_BOOKINGS_START = 'CONFIRM_BOOKINGS_START',
                CONFIRM_BOOKINGS_SUCCESS = 'CONFIRM_BOOKINGS_SUCCESS',
                CONFIRM_BOOKINGS_FAILURE = 'CONFIRM_BOOKINGS_FAILURE';