export const    GET_BOOKINGS_START = 'GET_BOOKINGS_START',
                GET_BOOKINGS_SUCCESS = 'GET_BOOKINGS_SUCCESS',
                GET_BOOKINGS_FAILURE = 'GET_BOOKINGS_FAILURE';

export const    CONFIRM_BOOKINGS_START = 'CONFIRM_BOOKINGS_START',
                CONFIRM_BOOKINGS_SUCCESS = 'CONFIRM_BOOKINGS_SUCCESS',
                CONFIRM_BOOKINGS_FAILURE = 'CONFIRM_BOOKINGS_FAILURE';

export const    CREATE_BOOKING_START = 'CREATE_BOOKING_START',
                CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS',
                CREATE_BOOKING_FAILURE = 'CREATE_BOOKING_FAILURE';