export const GET_ALL_EQUIPMENTS_FOR_BOOKABLE_START = 'GET_ALL_EQUIPMENTS_FOR_BOOKABLE_START',
				GET_ALL_EQUIPMENTS_FOR_BOOKABLE_SUCCESS = 'GET_ALL_EQUIPMENTS_FOR_BOOKABLE_SUCCESS',
				GET_ALL_EQUIPMENTS_FOR_BOOKABLE_FAILURE = 'GET_ALL_EQUIPMENTS_FOR_BOOKABLE_FAILURE';

export const CREATE_EQUIPMENT_START = 'CREATE_EQUIPMENT_START',
				CREATE_EQUIPMENT_SUCCESS = 'CREATE_EQUIPMENT_SUCCESS',
				CREATE_EQUIPMENT_FAILURE = 'CREATE_EQUIPMENT_FAILURE';