// NOTE: post запрос на создание расписания тренера
export const    POST_START_SCHEDULE_TRAINER = 'POST_START_SCHEDULE_TRAINER',
                POST_SUCCESS_SCHEDULE_TRAINER = 'POST_SUCCESS_SCHEDULE_TRAINER',
                POST_FAILURE_SCHEDULE_TRAINER = 'POST_FAILURE_SCHEDULE_TRAINER';

// NOTE: get запрос на получение расписания тренера
export const    GET_START_SCHEDULE_TRAINER = 'GET_START_SCHEDULE_TRAINER',
                GET_SUCCESS_SCHEDULE_TRAINER = 'GET_SUCCESS_SCHEDULE_TRAINER',
                GET_FAILURE_SCHEDULE_TRAINER = 'GET_FAILURE_SCHEDULE_TRAINER';

export const    EDIT_START_SCHEDULE_TRAINER = 'EDIT_START_SCHEDULE_TRAINER',
                EDIT_SUCCESS_SCHEDULE_TRAINER = 'EDIT_SUCCESS_SCHEDULE_TRAINER',
                EDIT_FAILURE_SCHEDULE_TRAINER = 'EDIT_FAILURE_SCHEDULE_TRAINER';

export const    TOGGLE_RESPONSE = 'TOGGLE_RESPONSE';

// Note: запрос на отмену подтвержденного забронированного времени
export const    DECLINE_CONFIRM_BOOKING_START = 'DECLINE_CONFIRM_BOOKING_START',
                DECLINE_CONFIRM_BOOKING_SUCCESS = 'DECLINE_CONFIRM_BOOKING_SUCCESS',
                DECLINE_CONFIRM_BOOKING_FAILURE = 'DECLINE_CONFIRM_BOOKING_FAILURE';