export const GET_SCHEDULE_CHOOSE_DAY = 'GET_SCHEDULE_CHOOSE_DAY';

// NOTE: post запрос на создание расписания тренера
export const POST_START_SCHEDULE_TRAINER = 'POST_START_SCHEDULE_TRAINER';
export const POST_SUCCESS_SCHEDULE_TRAINER = 'POST_SUCCESS_SCHEDULE_TRAINER';
export const POST_FAILURE_SCHEDULE_TRAINER = 'POST_FAILURE_SCHEDULE_TRAINER';

export const GET_START_SCHEDULE_TRAINER = 'GET_START_SCHEDULE_TRAINER',
            GET_SUCCESS_SCHEDULE_TRAINER = 'GET_SUCCESS_SCHEDULE_TRAINER',
            GET_FAILURE_SCHEDULE_TRAINER = 'GET_FAILURE_SCHEDULE_TRAINER';