
export const GET_START_SEARCH_PLAYGROUND = 'GET_START_SEARCH_PLAYGROUND',
                GET_SUCCESS_SEARCH_PLAYGROUND = 'GET_SUCCESS_SEARCH_PLAYGROUND',
                GET_FAILURE_SEARCH_PLAYGROUND = 'GET_FAILURE_SEARCH_PLAYGROUND',
                CLEAR_SEARCH_PLAYGROUND = 'CLEAR_SEARCH_PLAYGROUND';
 
