export const    GET_TRAINER_LIST_START = 'GET_TRAINER_LIST_START',
                GET_TRAINER_LIST_SUCCESS = 'GET_TRAINER_LIST_SUCCESS',
                GET_TRAINER_LIST_FAILURE = 'GET_TRAINER_LIST_FAILURE';