export const    GET_TRAINER_LIST_START = 'GET_TRAINER_LIST_START',
                GET_TRAINER_LIST_SUCCESS = 'GET_TRAINER_LIST_SUCCESS',
                GET_TRAINER_LIST_FAILURE = 'GET_TRAINER_LIST_FAILURE';

export const    CLEAR_TRAINER_LIST_STORE = 'CLEAR_TRAINER_LIST_STORE';