export const GET_TRAINER_INFO_START = 'GET_TRAINER_INFO_START',
                GET_TRAINER_INFO_SUCCESS = 'GET_TRAINER_INFO_SUCCESS',
                GET_TRAINER_INFO_FAILURE = 'GET_TRAINER_INFO_FAILURE';